'name' => 'midcom.helper.imagepopup',
'icon' => 'stock-icons/16x16/attach.png',
'description' => 'Image upload and insertion tool',
'purecode' => true,
'version' => '9.0.0',
'state' => 'stable',
'privileges' => array(),
'class_mapping' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'maintainers' => array
    (
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
        ),
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
            'active' => 'no',
        ),
        'netblade' => array
        (
            'name' => 'Oskari Kokko',
            'email' => 'oskari.kokko@nemein.com',
            'role' => 'developer',
        ),
        'w_i' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@nemein.com',
            'role' => 'developer',
            'active' => 'no',
        ),
        'jbergius' => array
        (
            'name' => 'Joonas Bergius',
            'email' => 'joonas.bergius@gmail.com',
            'role' => 'developer',
        ),
    ),
    'dependencies' => array
    (
        'midcom.helper.datamanager2' => array(),
        'midcom' => array(),
    ),
),
