'name' => 'midcom.helper.reflector',
'purecode' => true,
'version' => '9.0.0',
'icon' => 'stock-icons/16x16/stock_folder-properties.png',
'state' => 'stable',
'privileges' => array(),
'class_mapping' => array(),
'package.xml' => array
(
    'summary' => 'MidCOM reflection helper',
    'description' => 'Contains helper methods for shortcutting common reflection based tasks',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'rambo@nemein.com',
            'role' => 'lead',
        ),
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'developer',
        ),
    ),
),
