'name' => 'fi.protie.navigation',
'icon' => 'fi.protie.navigation/navigation.png',
'version' => '9.0.0',
'state' => 'stable',
'purecode' => true,
'package.xml' => array
(
    'summary' => 'Dynamic navigation',
    'description' => 'Versatile class for drawing dynamically navigation elements according to user preferences.',
    'maintainers' => array
    (
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu.manninen@protie.fi',
            'role' => 'lead',
        ),
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
            'active' => 'no',
        ),
        'netblade' => array
        (
            'name' => 'Oskari Kokko',
            'email' => 'oskari.kokko@iki.fi',
            'role' => 'lead',
        ),
        'w_i' => array
        (
            'name' => 'Jerry Jalava',
            'email' => 'jerry.jalava@gmail.com',
            'role' => 'developer',
            'active' => 'no',
        ),
    ),
    'dependencies' => array(),
),
