'schemadb' => 'file:/org/openpsa/calendar/config/schemadb_default.inc',
'schemadb_resource' => 'file:/org/openpsa/calendar/config/schemadb_resource.inc',
'schemadb_filters' => 'file:/org/openpsa/calendar/config/schemadb_filters.inc',

'schemadb_config' => 'file:/org/openpsa/calendar/config/schemadb_config.inc',

'calendar_root_event' => false,

'holidays_country' => '',
'holidays_region' => null,

'day_start_time'   => 8,   // hour 'working day' starts
'day_end_time'     => 18,  // hour 'working day' ends
'show_group_subscribers' => false, // whether to show members of 'subscriber' groups
'start_view' => 'week', // which view to start in
'wiki_title_skeleton' => 'meeting note for %s on %s by %s', //format of wiki page title created from event
'event_label'       => 'title',

