'schemadb' => 'file:/org/openpsa/calendar/config/schemadb_default.inc',
'schemadb_filters' => 'file:/org/openpsa/calendar/config/schemadb_filters.inc',

'schemadb_config' => 'file:/org/openpsa/calendar/config/schemadb_config.inc',

'calendar_root_event' => false,

'week_slot_length' => 120, // minutes
'day_slot_length'  => 60,  // minutes
'day_start_time'   => 8,   // hour 'working day' starts
'day_end_time'     => 18,  // hour 'working day' ends
'calendar_popup_width'   => 500, // width of the popup in pixels
'calendar_popup_height'  => 550, // height of the popup in pixels
'show_group_subscribers' => false, // whether to show members of 'subscriber' groups
'start_view' => 'week', // which view to start in
'wiki_title_skeleton' => 'meeting note for %s on %s by %s', //format of wiki page title created from event
'always_show_group' => null,
'always_show_self'  => true,
'event_label'       => 'title',

