array(
    'mgdschema_class_name' => 'org_openpsa_event',
    'midcom_class_name' => 'org_openpsa_calendar_event_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_eventmember',
    'midcom_class_name' => 'org_openpsa_calendar_event_member_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_calendar_resource',
    'midcom_class_name' => 'org_openpsa_calendar_resource_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_calendar_event_resource',
    'midcom_class_name' => 'org_openpsa_calendar_event_resource_dba'
),