array
(
    'mgdschema_class_name' => 'midcom_core_temporary_object_db',
    'midcom_class_name' => 'midcom_core_temporary_object'
),
array
(
    'mgdschema_class_name' => 'midcom_core_group_virtual_db',
    'midcom_class_name' => 'midcom_baseclasses_database_group_virtual'
),
array
(
    'mgdschema_class_name' => 'midcom_core_privilege_db',
    'midcom_class_name' => 'midcom_baseclasses_database_privilege'
),
