'da' => Array (
    'enname' => 'Danish',
    'locale' => 'da_DK',
    'localname' => 'Dansk',
    'encoding' => 'UTF-8',
    'midgard_code' => 'da',
),

'nl' => Array (
    'enname' => 'Dutch',
    'locale' => 'nl_NL',
    'localname' => 'Nederlands',
    'encoding' => 'UTF-8',
    'midgard_code' => 'nl',
),

'en' => Array (
    'enname' => 'English',
    'locale' => 'en_GB',
    'localname' => 'English',
    'encoding' => 'UTF-8',
    'midgard_code' => 'en-gb',
),

'et' => Array (
    'enname' => 'Estonian',
    'locale' => 'et_EE',
    'localname' => 'Eesti',
    'encoding' => 'UTF-8',
    'midgard_code' => 'et',
),

'fi' => Array (
    'enname' => 'Finnish',
    'locale' => array('fi_FI.UTF-8', 'fi_FI'),
    'localname' => 'Suomi',
    'encoding' => 'UTF-8',
    'midgard_code' => 'fi',
),

'fr' => Array (
    'enname' => 'French',
    'locale' => 'fr_FR',
    'localname' => 'Français',
    'encoding' => 'UTF-8',
    'midgard_code' => 'fr',
),

'ka' => Array (
    'enname' => 'Georgian',
    'locale' => 'ge_LA',
    'localname' => '&#4325;&#4304;&#4320;&#4311;&#4323;&#4314;&#4312;',
    'encoding' => 'UTF-8',
    'midgard_code' => 'ka',
),

'de' => Array (
    'enname' => 'German',
    'locale' => Array('de_DE.UTF-8', 'de_DE@UTF-8', 'de_DE'),
    'localname' => 'Deutsch',
    'encoding' => 'UTF-8',
    'midgard_code' => 'de',
),

'it' => Array (
    'enname' => 'Italian',
    'locale' => array('it_IT.UTF-8@euro', 'it_IT'),
    'localname' => 'Italiano',
    'encoding' => 'UTF-8',
    'midgard_code' => 'it',
),

'no' => Array (
    'enname' => 'Norwegian',
    'locale' => 'no_NO',
    'localname' => 'Norsk',
    'encoding' => 'UTF-8',
    'midgard_code' => 'no',
),

'pl' => Array (
    'enname' => 'Polish',
    'locale' => 'pl_PL',
    'localname' => 'Polski',
    'encoding' => 'UTF-8',
    'midgard_code' => 'pl',
),

'pt' => Array ( 
    'enname' => 'Portuguese',
    'locale' => 'pt_BR', 
    'localname' => 'Português', 
    'encoding' => 'UTF-8',
    'midgard_code' => 'pt', 
),

'ru' => Array (
    'enname' => 'Russian',
    'locale' => 'ru_RU',
    'localname' => 'Русский',
    'encoding' => 'UTF-8',
    'midgard_code' => 'ru',
),

'es' => Array (
    'enname' => 'Spanish',
    'locale'=>'es_MX',
    'localname' => 'Español',
    'encoding' => 'UTF-8',
    'midgard_code' => 'es',
),

'sv' => Array (
    'enname' => 'Swedish',
    'locale' => array('sv_SE.UTF-8', 'sv_SE'),
    'localname' => 'Svenska',
    'encoding' => 'UTF-8',
    'midgard_code' => 'sv',
),

'hu' => Array (
    'enname' => 'Hungarian',
    'locale' => array('hu_HU.UTF-8', 'hu_HU'),
    'localname' => 'Magyar',
    'encoding' => 'UTF-8',
    'midgard_code' => 'hu',
),

'zh' => Array (
    'enname' => 'Chinese',
    'locale' => 'zh_CN',
    'localname' => '中文',
    'encoding' => 'UTF-8',
    'midgard_code' => 'zh',
),