array
(
    'mgdschema_class_name' => 'midgard_article',
    'midcom_class_name' => 'midcom_db_article'
),
array
(
    'mgdschema_class_name' => 'midgard_attachment',
    'midcom_class_name' => 'midcom_db_attachment'
),
array
(
    'mgdschema_class_name' => 'midgard_element',
    'midcom_class_name' => 'midcom_db_element'
),
array
(
    'mgdschema_class_name' => 'midgard_event',
    'midcom_class_name' => 'midcom_db_event'
),
array
(
    'mgdschema_class_name' => 'midgard_eventmember',
    'midcom_class_name' => 'midcom_db_eventmember'
),
array
(
    'mgdschema_class_name' => 'midgard_group',
    'midcom_class_name' => 'midcom_db_group'
),
array
(
    'mgdschema_class_name' => 'midgard_host',
    'midcom_class_name' => 'midcom_db_host'
),
array
(
    'mgdschema_class_name' => 'midgard_language',
    'midcom_class_name' => 'midcom_db_language'
),
array
(
    'mgdschema_class_name' => 'midgard_member',
    'midcom_class_name' => 'midcom_db_member'
),
array
(
    'mgdschema_class_name' => 'midgard_page',
    'midcom_class_name' => 'midcom_db_page'
),
array
(
    'mgdschema_class_name' => 'midgard_pageelement',
    'midcom_class_name' => 'midcom_db_pageelement'
),
array
(
    'mgdschema_class_name' => 'midgard_parameter',
    'midcom_class_name' => 'midcom_db_parameter'
),
array
(
    'mgdschema_class_name' => $GLOBALS['midcom_config']['person_class'],
    'midcom_class_name' => 'midcom_db_person'
),
array
(
    'mgdschema_class_name' => 'midgard_snippet',
    'midcom_class_name' => 'midcom_db_snippet'
),
array
(
    'mgdschema_class_name' => 'midgard_snippetdir',
    'midcom_class_name' => 'midcom_db_snippetdir'
),
array
(
    'mgdschema_class_name' => 'midgard_style',
    'midcom_class_name' => 'midcom_db_style'
),
array
(
    'mgdschema_class_name' => 'midgard_topic',
    'midcom_class_name' => 'midcom_db_topic'
),
