array
(
    'mgdschema_class_name' => 'midgard_article',
    'midcom_class_name' => 'midcom_baseclasses_database_article'
),
array
(
    'mgdschema_class_name' => 'midgard_attachment',
    'midcom_class_name' => 'midcom_baseclasses_database_attachment'
),
array
(
    'mgdschema_class_name' => 'midgard_element',
    'midcom_class_name' => 'midcom_baseclasses_database_element'
),
array
(
    'mgdschema_class_name' => 'midgard_event',
    'midcom_class_name' => 'midcom_baseclasses_database_event'
),
array
(
    'mgdschema_class_name' => 'midgard_eventmember',
    'midcom_class_name' => 'midcom_baseclasses_database_eventmember'
),
array
(
    'mgdschema_class_name' => 'midgard_group',
    'midcom_class_name' => 'midcom_baseclasses_database_group'
),
array
(
    'mgdschema_class_name' => 'midgard_host',
    'midcom_class_name' => 'midcom_baseclasses_database_host'
),
array
(
    'mgdschema_class_name' => 'midgard_language',
    'midcom_class_name' => 'midcom_baseclasses_database_language'
),
array
(
    'mgdschema_class_name' => 'midgard_member',
    'midcom_class_name' => 'midcom_baseclasses_database_member'
),
array
(
    'mgdschema_class_name' => 'midgard_page',
    'midcom_class_name' => 'midcom_baseclasses_database_page'
),
array
(
    'mgdschema_class_name' => 'midgard_pageelement',
    'midcom_class_name' => 'midcom_baseclasses_database_pageelement'
),
array
(
    'mgdschema_class_name' => 'midgard_parameter',
    'midcom_class_name' => 'midcom_baseclasses_database_parameter'
),
array
(
    'mgdschema_class_name' => $GLOBALS['midcom_config']['person_class'],
    'midcom_class_name' => 'midcom_baseclasses_database_person'
),
array
(
    'mgdschema_class_name' => 'midgard_snippet',
    'midcom_class_name' => 'midcom_baseclasses_database_snippet'
),
array
(
    'mgdschema_class_name' => 'midgard_snippetdir',
    'midcom_class_name' => 'midcom_baseclasses_database_snippetdir'
),
array
(
    'mgdschema_class_name' => 'midgard_style',
    'midcom_class_name' => 'midcom_baseclasses_database_style'
),
array
(
    'mgdschema_class_name' => 'midgard_topic',
    'midcom_class_name' => 'midcom_baseclasses_database_topic'
),
