'name' => 'org.openpsa.smslib',
'icon' => 'stock-icons/16x16/stock_cell-phone.png',
'purecode' => true,
'privileges' => array(),
'class_mapping' => array(),
'version' => '9.0beta1',
'state' => 'stable',
'package.xml' => array
(
    'summary' => 'SMS sending library',
    'description' => 'Library for transmitting SMS messages through different gateways',
    'maintainers' => array
    (
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
