'default_workgroup_filter' => 'all',
'owner_organization' => null, // Set to GUID of org_openpsa_organization
'auto_init' => true,

//the name of page used for jquery ui-tab - if the page doesn't exist
// it will be created in siteconfig - the style is passed in templates/OpenPsa2
'ui_page' => 'uitab',

'jqgrid_version' => '3.8.1',

// These values are automatically set when org_openpsa_core structure is first called
// To trigger another auto-detection, simply set auto_int to true in the config snippet
    'calendar_guid'         => false,
    'calendar_full_url'     => false,
    'calendar_relative_url' => false,
    'contacts_guid'         => false,
    'contacts_full_url'     => false,
    'contacts_relative_url' => false,
    'documents_guid'         => false,
    'documents_full_url'     => false,
    'documents_relative_url' => false,
    'expenses_guid'         => false,
    'expenses_full_url'     => false,
    'expenses_relative_url' => false,
    'invoices_guid'         => false,
    'invoices_full_url'     => false,
    'invoices_relative_url' => false,
    'projects_guid'         => false,
    'projects_full_url'     => false,
    'projects_relative_url' => false,
    'reports_guid'          => false,
    'reports_full_url'      => false,
    'reports_relative_url'  => false,
    'sales_guid'            => false,
    'sales_full_url'        => false,
    'sales_relative_url'    => false,
    'search_guid'           => false,
    'search_full_url'       => false,
    'search_relative_url'   => false,
    'wiki_guid'             => false,
    'wiki_full_url'         => false,
    'wiki_relative_url'     => false,
