'name' => 'org.openpsa.calendarwidget',
'icon' => 'org.openpsa.calendarwidget/calendar-widget-renderer.png',
'purecode' => true,
'privileges' => array(),
'class_definitions' => array(),
'version' => '8.09.9',
'state' => 'stable',
'package.xml' => array
(
    'summary' => 'Widget for drawing calendar views',
    'description' => 'Supports day, week and month views, with configurable slot sizes',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
            'active' => 'no',
        ),
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
        ),
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu.manninen@protie.fi',
            'role' => 'lead',
        ),
        'netblade' => array
        (
            'name' => 'Oskari Kokko',
            'email' => 'oskari.kokko@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
