'name' => 'org.openpsa.widgets',
'purecode' => true,
'privileges' => array(),
'class_mapping' => array(),
'version' => '9.1.0-dev',
'state' => 'stable',
'package.xml' => array
(
    'summary' => 'OpenPSA common UI elements',
    'description' => 'Widgets for OpenPSA',
    'maintainers' => array
    (
        'flack' => array
        (
            'name' => 'Andreas Flack',
            'email' => 'flack@contentcontrol-berlin.de',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'org.openpsa.core' => array(),
        'midcom' => array(),
    ),
),