'name' => 'org.openpsa.slideshow',
'purecode' => false,
'class_mapping' => array
(
    'org_openpsa_slideshow_image' => 'org_openpsa_slideshow_image_dba',
),
'version' => '9.1.0-dev',
'state' => 'stable',
'package.xml' => array
(
    'summary' => 'OpenPSA Slideshow',
    'description' => 'Simple Slideshow/Image Gallery Viewer',
    'maintainers' => array
    (
        'flack' => array
        (
            'name' => 'Andreas Flack',
            'email' => 'flack@contentcontrol-berlin.de',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
