'name' => 'net.nehmer.markdown',
'icon' => 'net.nehmer.markdown/markdown.png',
'version' => '8.09.9',
'state' => 'stable',
'purecode' => true,
'package.xml' => array
(
    'summary' => 'Markdown formatter',
    'description' => 'PHP Markdown is a port to PHP of the Markdown program written by John Gruber.',
    'maintainers' => array
    (
        'torben' => array
        (
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
            'active' => 'no',
        ),
        'rambo' => array
        (
            'name' => 'Eero af Heurlin',
            'email' => 'eero.afheurlin@iki.fi',
            'role' => 'lead',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
