/**
 * This is the configuration file for the module.
 * This is where you set default values for different configuration variables
 */
/* The sort order to use */
'sort_order' => 'score',

/* The schema database to use */
'schemadb' => 'file:/net/nemein/tag/config/schemadb_default.inc',

/* The schema in the database to use to edit articles 
 * note the name here and in schemadb_default.inc
 * This is used when having created the complete crud component - not just the basic one. 
 * */
'schema' => 'default',
