'name' => 'midcom.helper.search',
'icon' => 'stock-icons/16x16/search.png',
'version' => '9.1.0-dev',
'state' => 'stable',
'purecode' => false,
'privileges' => array(),
'class_mapping' => array(),
'package.xml' => array
(
    'summary' => 'Search tool',
    'description' => 'Front-end for the Lucene search engine',
    'maintainers' => array
    (
        'torben' => array
        (
            'name' => 'Torben Nehmer',
            'email' => 'torben@nehmer.net',
            'role' => 'lead',
            'active' => 'no',
        ),
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
