"schemadb_queryform_projects" => "file:/org/openpsa/reports/config/schemadb_default_queryform_projects.inc",
"schemadb_queryform_sales" => "file:/org/openpsa/reports/config/schemadb_default_queryform_sales.inc",
"schemadb_queryform_invoices" => "file:/org/openpsa/reports/config/schemadb_default_queryform_invoices.inc",
'temporary_report_max_age'  =>  3, //Days

'subscription_profit_months' => 12,
