/*
'config' => array (
    'name'        => 'config',
    'description' => 'Default Configuration Schema', 
    'locktimeout' => 0, 
    'fields'      => array (
            'imp_global_uri' => array ( 
                'description'   => 'Global URL for Horde/Imp login',
                'datatype'      => 'text',
                'location'      => 'config',
                'config_domain' => 'org.openpsa.imp',
                'config_key'    => 'imp_global_uri',
            ),
    ),
),
*/