'name' => 'org.openpsa.helpers',
'purecode' => true,
'privileges' => array(),
'class_mapping' => array(),
'version' => '9.1.0',
'state' => 'stable',
'description' => 'OpenPSA helpers for AJAX and workgroup filtering, and some common housekeeping tasks',
'customdata' => array
(
    'request_handler_plugin' => array
    (
        'class' => 'org_openpsa_helpers_plugin',
        'name' => 'OpenPSA helpers',
        'config' => '',
    ),
),
