'name' => 'de.bitfolge.feedcreator',
'icon' => 'net.nemein.rss/rss-16.png',
'purecode' => true,
'version' => '9.0beta4+git',
'state' => 'stable',
'privileges' => array(),
'class_mapping' => array(),
'package.xml' => array
(
    'summary' => 'News feed generator',
    'description' => 'RSS and Atom feed generator by Kai Blankenhorn',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
