'history' =>  Array
(
    'handler' => array('midcom_admin_rcs_handler_rcs', 'history'),
    'variable_args' => 1,
),

'preview' =>  Array
(
    'fixed_args' => array('preview'),
    'handler' => array('midcom_admin_rcs_handler_rcs', 'preview'),
    'variable_args' => 2,
),
'diff' =>  Array
(
    'fixed_args' => array('diff'),
    'handler' => array('midcom_admin_rcs_handler_rcs', 'diff'),
    'variable_args' => 3,
),
'restore' =>  Array
(
    'fixed_args' => array('restore'),
    'handler' => array('midcom_admin_rcs_handler_rcs', 'restore'),
    'variable_args' => 2,
),
