'history' =>  Array
(
    'handler' => array('midcom_admin_rcs_handler','history'),
    'variable_args' => 1,
),

'preview' =>  Array
(
    'fixed_args' => array('preview'),
    'handler' => array('midcom_admin_rcs_handler','preview'),
    'variable_args' => 2,
),
'diff' =>  Array
(
    'fixed_args' => array('diff'),
    'handler' => array('midcom_admin_rcs_handler','diff'),
    'variable_args' => 3,
),
'restore' =>  Array
(
    'fixed_args' => array('restore'),
    'handler' => array('midcom_admin_rcs_handler','restore'),
    'variable_args' => 2,
),
