array(
    'mgdschema_class_name' => 'org_openpsa_campaign',
    'midcom_class_name' => 'org_openpsa_directmarketing_campaign_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_campaign_member',
    'midcom_class_name' => 'org_openpsa_directmarketing_campaign_member_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_campaign_message',
    'midcom_class_name' => 'org_openpsa_directmarketing_campaign_message_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_campaign_message_receipt',
    'midcom_class_name' => 'org_openpsa_directmarketing_campaign_message_receipt_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_link_log',
    'midcom_class_name' => 'org_openpsa_directmarketing_link_log_dba'
)