array(
    'mgdschema_class_name' => 'org_openpsa_task',
    'midcom_class_name' => 'org_openpsa_projects_task_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_task_resource',
    'midcom_class_name' => 'org_openpsa_projects_task_resource_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_task_status',
    'midcom_class_name' => 'org_openpsa_projects_task_status_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_hour_report',
    'midcom_class_name' => 'org_openpsa_projects_hour_report_dba'
),