#!/bin/sh
# postinst script for openpsa2

php5 /usr/share/openpsa2/quick_init.php
RETVAL=$?
[ $RETVAL -ne 0 ] && exit 1

# Ensure web server can write to database and blobs
chown -R www-data:www-data /var/lib/openpsa2

exit 0
