/**
 * This is the configuration file for the module.
 * This is where you set default values for different configuration variables
 */

/* The schema database to use */
'schemadb_hours' => 'file:/org/openpsa/expenses/config/schemadb_default_hours.inc',
'schemadb_hours_simple' => 'file:/org/openpsa/expenses/config/schemadb_default_hours_simple.inc',
/* schema with the needed widgets for the batch-handler */
'schemadb_widgets_batch' => 'file:/org/openpsa/expenses/config/schemadb_widgets_batch.inc',
