'schemadb_salesproject' => 'file:/org/openpsa/sales/config/schemadb_default.php',
'schemadb_deliverable' => 'file:/org/openpsa/sales/config/schemadb_deliverable_default.php',
'new_wikinote_wikiword_format' => 'note to "%s" on %s',
'subscription_profit_months' => 12,
'subscription_invoice_day_of_month' => false,

'calculator' => 'org_openpsa_sales_calculator_default',
//contains the class file to create the pdf for the sales, if set to false pdf-creation is disabled
'sales_pdfbuilder_class' => false, //implements org_openpsa_sales_interfaces_pdfbuilder
'schemadb_pdf' => 'file:/org/openpsa/sales/config/schemadb_offer_default.php',