array(
    'mgdschema_class_name' => 'org_openpsa_salesproject',
    'midcom_class_name' => 'org_openpsa_sales_salesproject_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_salesproject_member',
    'midcom_class_name' => 'org_openpsa_sales_salesproject_member_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_salesproject_deliverable',
    'midcom_class_name' => 'org_openpsa_sales_salesproject_deliverable_dba'
),