'schemadb_config' => 'file:/net/nemein/redirector/config/schemadb_config.inc',
'schemadb_tinyurl' => 'file:/net/nemein/redirector/config/schemadb_tinyurl.inc',
'redirection_type' => null, // subnode or url
'redirection_url'  => '',
'redirection_code' => 301,
'redirection_node' => null,
'redirection_guid'  => null,
'redirection_metatag' => false,
'redirection_metatag_speed' => 5,

'admin_redirection' => true,
