'schemadb_group' => 'file:/org/openpsa/contacts/config/schemadb_default_organization.inc',
'schemadb_person' => 'file:/org/openpsa/contacts/config/schemadb_default_person.inc',

'schemadb_config' => 'file:/org/openpsa/contacts/config/schemadb_config.inc',

'person_search_fields' => 'username,firstname,lastname,email',
'organization_search_fields' => 'official,email,name,customerId',
'enable_duplicate_search' => false, /* NOTE: These are *very* heavy cron jobs run daily */
'auto_wildcards' => 'end',
