'name' => 'openpsa.unittest.testcomponent',
'version' => '9.0dummy',
'state' => 'stable',
'class_mapping' => array(),
'package.xml' => array
(
    'summary' => 'Dummy component',
    'description' => 'This is used to test loading components outside of MIDCOM_ROOT',
    'maintainers' => array
    (
        'flack' => array
        (
            'name' => 'Andreas Flack',
            'email' => 'flack@contentcontrol-berlin.de',
            'role' => 'lead',
            'active' => 'yes',
        ),
    ),
    'dependencies' => array(),
),
