'name' => 'midcom.helper.filesync',
'icon' => 'stock-icons/16x16/stock_refresh.png',
'purecode' => true,
'version' => '9.1.0-dev',
'state' => 'stable',
'privileges' => array(),
'package.xml' => array
(
    'summary' => 'Site template filesystem synchronization',
    'description' => 'Site template filesystem synchronization',
    'maintainers' => array
    (
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'lead',
        ),
    ),
),
