array(
    'mgdschema_class_name' => 'org_openpsa_invoice',
    'midcom_class_name' => 'org_openpsa_invoices_invoice_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_invoice_hour',
    'midcom_class_name' => 'org_openpsa_invoices_invoice_hour_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_invoice_item',
    'midcom_class_name' => 'org_openpsa_invoices_invoice_item_dba'
),
array(
    'mgdschema_class_name' => 'org_openpsa_billing_data',
    'midcom_class_name' => 'org_openpsa_invoices_billing_data_dba'
),