'name' => 'org.openpsa.notifications',
'icon' => 'org.openpsa.notifications/notification-system.png',
'purecode' => true,
'privileges' => array(),
'version' => '9.1.0-dev',
'state' => 'stable',
'class_mapping' => array
(
    'org_openpsa_notifications_notification' => 'org_openpsa_notifications_notification_dba',
),
'description' => 'System for sending notifications to users based on their preferences',