'name' => 'midcom.datamanager',
'version' => '9.0.0-rc.3+git',
'state' => 'stable',
'purecode' => true,
'package.xml' => array
(
    'summary' => 'Data abstraction and form rendering library',
    'description' => 'Datamanager is a MidCOM purecode component providing database abstraction and form processing features',
    'state' => 'stable',
    'maintainers' => array
    (
        'flack' => array
        (
            'name' => 'Andreas Flack',
            'email' => 'flack@contentcontrol-berlin.de',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
        'midcom.helper.imagepopup' => array(),
    ),
),
