'name' => 'midcom.admin.help',
'icon' => 'stock-icons/16x16/stock_help-agent.png',
'description' => 'On-site help displayer',
'purecode' => true,
'version' => '9.0.0',
'state' => 'stable',
'privileges' => array(),
'class_mapping' => array(),
'package.xml' => array
(
    'license' => 'GPL',
    'maintainers' => array
    (
        'tarjei' => array
        (
            'name' => 'Tarjei Huse',
            'email' => 'tarjei@nu.no',
            'role' => 'lead',
            'active' => 'no',
        ),
        'adrenalin' => array
        (
            'name' => 'Arttu Manninen',
            'email' => 'arttu@kaktus.cc',
            'role' => 'developer',
        ),
        'bergie' => array
        (
            'name' => 'Henri Bergius',
            'email' => 'henri.bergius@iki.fi',
            'role' => 'developer',
        ),
        'solt' => array
        (
            'name' => 'Marcin Sołtysiak',
            'email' => 'office@imedia.com.pl',
            'active' => 'yes',
            'role' => 'lead',
        ),
    ),
    'dependencies' => array
    (
        'midcom' => array(),
    ),
),
